disable ruby-head b/c sorbet failing
-----> [Sorbet Example Project] Nuking and regenerating Mocktail RBI files
<internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- racc/parser (LoadError)
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/parser-3.2.2.1/lib/parser.rb:12:in `<top (required)>'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/rbi-0.0.16/lib/rbi/parser.rb:4:in `<top (required)>'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/rbi-0.0.16/lib/rbi.rb:24:in `<top (required)>'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/tapioca-0.11.6/lib/tapioca/dsl.rb:4:in `<top (required)>'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/home/runner/.rubies/ruby-head/lib/ruby/3.3.0+0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/tapioca-0.11.6/lib/tapioca/internal.rb:58:in `<top (required)>'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/tapioca-0.11.6/exe/tapioca:23:in `require_relative'
	from /home/runner/.rubies/ruby-head/lib/ruby/gems/3.3.0+0/gems/tapioca-0.11.6/exe/tapioca:23:in `<top (required)>'
	from bin/tapioca:27:in `load'
	from bin/tapioca:27:in `<main>'
Error: Process completed with exit code 1.