sorbet-eraser 0.4.0 regressions
./script/test fails with:

-----> Running Mocktail's test against lib
+ MOCKTAIL_TEST_SRC_DIRECTORY=lib
+ bundle exec rake
/Users/justin/code/testdouble/mocktail/lib/mocktail/debug.rb:17:in `<module:Debug>': undefined method `sig' for Mocktail::Debug:Module (NoMethodError)

    sig { void }
    ^^^
        from /Users/justin/code/testdouble/mocktail/lib/mocktail/debug.rb:2:in `<module:Mocktail>'
        from /Users/justin/code/testdouble/mocktail/lib/mocktail/debug.rb:1:in `<top (required)>'
        from /Users/justin/code/testdouble/mocktail/lib/mocktail.rb:15:in `require_relative'
        from /Users/justin/code/testdouble/mocktail/lib/mocktail.rb:15:in `<top (required)>'
        from /Users/justin/code/testdouble/mocktail/test/test_helper.rb:13:in `require'
        from /Users/justin/code/testdouble/mocktail/test/test_helper.rb:13:in `<top (required)>'
        from /Users/justin/code/testdouble/mocktail/test/mocktail_test.rb:3:in `require'
        from /Users/justin/code/testdouble/mocktail/test/mocktail_test.rb:3:in `<top (required)>'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
        from /Users/justin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'
rake aborted!
Command failed with status (1)
/Users/justin/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
/Users/justin/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)